// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /bus-positions"
  | "GET /buses"
  | "GET /devices"
  | "GET /routes"
  | "PATCH /buses/{busId}"
  | "PATCH /devices/{deviceId}"
  | "PATCH /routes/{routeId}"
  | "POST /buses"
  | "POST /devices"
  | "POST /location-updates"
  | "POST /routes";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /bus-positions": { kind: "scope", scope: "positions:read" },
  "GET /buses": { kind: "scope", scope: "fleet:read" },
  "GET /devices": { kind: "scope", scope: "devices:read" },
  "GET /routes": { kind: "scope", scope: "fleet:read" },
  "PATCH /buses/{busId}": { kind: "scope", scope: "fleet:manage" },
  "PATCH /devices/{deviceId}": { kind: "scope", scope: "devices:manage" },
  "PATCH /routes/{routeId}": { kind: "scope", scope: "fleet:manage" },
  "POST /buses": { kind: "scope", scope: "fleet:manage" },
  "POST /devices": { kind: "scope", scope: "devices:manage" },
  "POST /location-updates": { kind: "public" },
  "POST /routes": { kind: "scope", scope: "fleet:manage" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
