// GENERATED by scripts/gen-authz.mjs from specs/design/security.json roles[], in
// DECLARED order — the first is the default persona `?role=` falls back to.
// Do not edit by hand. Re-run `npm run gen` after the design changes.
//
// THE MOCK NEVER WIDENS: each role's grants are exactly what security.json
// declares. A role that cannot reach its own screen is a DESIGN DEFECT to
// report, never a mock to loosen.

export const mockRoles: readonly { readonly name: string; readonly grants: readonly string[] }[] = [
  { name: "Rider", grants: ["positions:read"] },
  { name: "Dispatcher", grants: ["devices:read", "positions:read"] },
  { name: "FleetAdmin", grants: ["devices:manage", "devices:read", "fleet:manage", "fleet:read"] },
];
