// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

// Foundation only (issue #3): every resource below is a stub that compiles
// and starts cleanly. None calls requireGatewayCaller(ctx) yet and none
// touches fleetDb — issue #5 fills in the real logic, operation by operation.
// The interceptor wiring itself (createInterceptors) is real: every request
// already passes through AssertionInterceptor from gateway_assertion.bal.
service http:InterceptableService / on ep0 {

    public function createInterceptors() returns AssertionInterceptor => new;

    resource function get bus\-positions(int 'limit = 20, int offset = 0) returns inline_response_200_3|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Every registered bus
    #
    # + return - returns can be any of following types
    # http:Ok (A page of buses)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function get buses(int 'limit = 20, int offset = 0) returns inline_response_200|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Every registered GPS device, including its last-update time
    #
    # + return - returns can be any of following types
    # http:Ok (A page of devices)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function get devices(int 'limit = 20, int offset = 0) returns inline_response_200_2|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Every route and its ordered stops
    #
    # + return - returns can be any of following types
    # http:Ok (A page of routes)
    # http:Unauthorized (not signed in)
    resource function get routes(int 'limit = 20, int offset = 0) returns inline_response_200_1|ErrorUnauthorized|error {
        return notImplemented();
    }

    # Update a bus's active status or route assignment
    #
    # + return - returns can be any of following types
    # http:Ok (bus updated)
    # http:BadRequest (invalid update)
    # http:NotFound (bus not found)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function patch buses/[string busId](@http:Payload BusUpdate payload) returns Bus|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Reassign a device to a different bus, or mark it active or inactive
    #
    # + return - returns can be any of following types
    # http:Ok (device updated)
    # http:BadRequest (invalid update)
    # http:NotFound (device not found)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function patch devices/[string deviceId](@http:Payload DeviceUpdate payload) returns Device|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Update a route's name or stops
    #
    # + return - returns can be any of following types
    # http:Ok (route updated)
    # http:BadRequest (invalid route)
    # http:NotFound (route not found)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function patch routes/[string routeId](@http:Payload NewRoute payload) returns Route|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Register a bus
    #
    # + return - returns can be any of following types
    # http:Created (bus registered)
    # http:BadRequest (invalid bus)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function post buses(@http:Payload NewBus payload) returns Bus|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    # Register a GPS device, issuing its ID and secret, and assign it to a bus
    #
    # + return - returns can be any of following types
    # http:Created (device registered)
    # http:BadRequest (invalid device)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function post devices(@http:Payload NewDevice payload) returns DeviceCredentials|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }

    resource function post location\-updates(@http:Payload LocationUpdate payload) returns http:Accepted|ErrorBadRequest|ErrorUnauthorized|error {
        return notImplemented();
    }

    # Define a route as an ordered sequence of named, located stops
    #
    # + return - returns can be any of following types
    # http:Created (route created)
    # http:BadRequest (invalid route)
    # http:Unauthorized (not signed in)
    # http:Forbidden (missing scope)
    resource function post routes(@http:Payload NewRoute payload) returns Route|ErrorBadRequest|ErrorUnauthorized|ErrorForbidden|error {
        return notImplemented();
    }
}

# Placeholder for every operation's business logic, which issue #5 implements.
# `|error` on each resource's return type is what makes `check`/this usable —
# `http` maps a returned error to 500, which is the right shape for "not built
# yet" since the contract never models this as a declared response.
#
# + return - an error, always
function notImplemented() returns error {
    return error("not implemented: this operation's business logic lands in issue #5");
}

public type NewBus record {
    string licensePlate;
};

public type Bus record {
    string id;
    string licensePlate;
    boolean active;
    string? routeId?;
};

public type Stop record {
    string name;
    # order of the stop along the route
    int sequence;
    decimal lat;
    decimal lng;
};

public type Device record {
    string id;
    string busId;
    boolean active;
    # when this device's last location update arrived
    string? lastUpdateAt?;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type DeviceCredentials record {
    string id;
    string busId;
    boolean active;
    # shown once, at registration
    string secret;
};

public type LocationUpdate record {
    string deviceId;
    string secret;
    decimal lat;
    decimal lng;
    string time;
};

public type NewRoute record {
    string name;
    Stop[] stops;
};

public type NewDevice record {
    string busId;
};

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type BusUpdate record {
    boolean active?;
    # route to assign; null clears the assignment
    string? routeId?;
};

public type inline_response_200_1 record {
    # total matching routes
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Route[] data;
};

public type BusPosition record {
    string busId;
    string? routeId?;
    decimal lat;
    decimal lng;
    string reportedAt;
    # true when no update has arrived for over 2 minutes
    boolean offline;
    # present only for a caller holding devices:read
    string deviceId?;
};

public type inline_response_200 record {
    # total matching buses
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Bus[] data;
};

public type inline_response_200_2 record {
    # total matching devices
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    Device[] data;
};

public type inline_response_200_3 record {
    # total matching buses
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    BusPosition[] data;
};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type DeviceUpdate record {
    # reassign the device to this bus
    string busId?;
    boolean active?;
};

public type Route record {
    string id;
    string name;
    Stop[] stops;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
